// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/auth_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/auth_repository.go -destination=internal/tests/mocks/auth_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	models "github.com/Iskolutions-Capstone-Dev-Team/One-Portal/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockAuthRepository is a mock of AuthRepository interface.
type MockAuthRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthRepositoryMockRecorder
	isgomock struct{}
}

// MockAuthRepositoryMockRecorder is the mock recorder for MockAuthRepository.
type MockAuthRepositoryMockRecorder struct {
	mock *MockAuthRepository
}

// NewMockAuthRepository creates a new mock instance.
func NewMockAuthRepository(ctrl *gomock.Controller) *MockAuthRepository {
	mock := &MockAuthRepository{ctrl: ctrl}
	mock.recorder = &MockAuthRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthRepository) EXPECT() *MockAuthRepositoryMockRecorder {
	return m.recorder
}

// CreateToken mocks base method.
func (m *MockAuthRepository) CreateToken(ctx context.Context, token models.RefreshToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateToken indicates an expected call of CreateToken.
func (mr *MockAuthRepositoryMockRecorder) CreateToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*MockAuthRepository)(nil).CreateToken), ctx, token)
}

// DeleteExpiredTokens mocks base method.
func (m *MockAuthRepository) DeleteExpiredTokens(ctx context.Context, at time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredTokens", ctx, at)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpiredTokens indicates an expected call of DeleteExpiredTokens.
func (mr *MockAuthRepositoryMockRecorder) DeleteExpiredTokens(ctx, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredTokens", reflect.TypeOf((*MockAuthRepository)(nil).DeleteExpiredTokens), ctx, at)
}

// DeleteToken mocks base method.
func (m *MockAuthRepository) DeleteToken(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteToken", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteToken indicates an expected call of DeleteToken.
func (mr *MockAuthRepositoryMockRecorder) DeleteToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteToken", reflect.TypeOf((*MockAuthRepository)(nil).DeleteToken), ctx, token)
}

// DeleteTokensByUserID mocks base method.
func (m *MockAuthRepository) DeleteTokensByUserID(ctx context.Context, userID []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTokensByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTokensByUserID indicates an expected call of DeleteTokensByUserID.
func (mr *MockAuthRepositoryMockRecorder) DeleteTokensByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTokensByUserID", reflect.TypeOf((*MockAuthRepository)(nil).DeleteTokensByUserID), ctx, userID)
}

// GetToken mocks base method.
func (m *MockAuthRepository) GetToken(ctx context.Context, token string) (models.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetToken", ctx, token)
	ret0, _ := ret[0].(models.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetToken indicates an expected call of GetToken.
func (mr *MockAuthRepositoryMockRecorder) GetToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetToken", reflect.TypeOf((*MockAuthRepository)(nil).GetToken), ctx, token)
}

// GetTokenByUserID mocks base method.
func (m *MockAuthRepository) GetTokenByUserID(ctx context.Context, userID []byte) (models.RefreshToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenByUserID", ctx, userID)
	ret0, _ := ret[0].(models.RefreshToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenByUserID indicates an expected call of GetTokenByUserID.
func (mr *MockAuthRepositoryMockRecorder) GetTokenByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenByUserID", reflect.TypeOf((*MockAuthRepository)(nil).GetTokenByUserID), ctx, userID)
}

// UpdateToken mocks base method.
func (m *MockAuthRepository) UpdateToken(ctx context.Context, token string, expiresAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateToken", ctx, token, expiresAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateToken indicates an expected call of UpdateToken.
func (mr *MockAuthRepositoryMockRecorder) UpdateToken(ctx, token, expiresAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateToken", reflect.TypeOf((*MockAuthRepository)(nil).UpdateToken), ctx, token, expiresAt)
}
