// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/log_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/log_service.go -destination=internal/tests/mocks/log_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Iskolutions-Capstone-Dev-Team/One-Portal/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockLogService is a mock of LogService interface.
type MockLogService struct {
	ctrl     *gomock.Controller
	recorder *MockLogServiceMockRecorder
	isgomock struct{}
}

// MockLogServiceMockRecorder is the mock recorder for MockLogService.
type MockLogServiceMockRecorder struct {
	mock *MockLogService
}

// NewMockLogService creates a new mock instance.
func NewMockLogService(ctrl *gomock.Controller) *MockLogService {
	mock := &MockLogService{ctrl: ctrl}
	mock.recorder = &MockLogServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogService) EXPECT() *MockLogServiceMockRecorder {
	return m.recorder
}

// GetLogs mocks base method.
func (m *MockLogService) GetLogs(ctx context.Context, actor string, limit, offset int) ([]models.Log, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLogs", ctx, actor, limit, offset)
	ret0, _ := ret[0].([]models.Log)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLogs indicates an expected call of GetLogs.
func (mr *MockLogServiceMockRecorder) GetLogs(ctx, actor, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogs", reflect.TypeOf((*MockLogService)(nil).GetLogs), ctx, actor, limit, offset)
}

// LogAction mocks base method.
func (m *MockLogService) LogAction(ctx context.Context, actor, action string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogAction", ctx, actor, action)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogAction indicates an expected call of LogAction.
func (mr *MockLogServiceMockRecorder) LogAction(ctx, actor, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogAction", reflect.TypeOf((*MockLogService)(nil).LogAction), ctx, actor, action)
}
