// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/user_access_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/user_access_repository.go -destination=internal/tests/mocks/user_access_repository_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Iskolutions-Capstone-Dev-Team/One-Portal/internal/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserAccessRepository is a mock of UserAccessRepository interface.
type MockUserAccessRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserAccessRepositoryMockRecorder
	isgomock struct{}
}

// MockUserAccessRepositoryMockRecorder is the mock recorder for MockUserAccessRepository.
type MockUserAccessRepositoryMockRecorder struct {
	mock *MockUserAccessRepository
}

// NewMockUserAccessRepository creates a new mock instance.
func NewMockUserAccessRepository(ctrl *gomock.Controller) *MockUserAccessRepository {
	mock := &MockUserAccessRepository{ctrl: ctrl}
	mock.recorder = &MockUserAccessRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserAccessRepository) EXPECT() *MockUserAccessRepositoryMockRecorder {
	return m.recorder
}

// CheckAccess mocks base method.
func (m *MockUserAccessRepository) CheckAccess(ctx context.Context, userID, clientID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAccess", ctx, userID, clientID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckAccess indicates an expected call of CheckAccess.
func (mr *MockUserAccessRepositoryMockRecorder) CheckAccess(ctx, userID, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAccess", reflect.TypeOf((*MockUserAccessRepository)(nil).CheckAccess), ctx, userID, clientID)
}

// GetAccessByClientID mocks base method.
func (m *MockUserAccessRepository) GetAccessByClientID(ctx context.Context, clientID uuid.UUID) ([]models.UserAccess, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessByClientID", ctx, clientID)
	ret0, _ := ret[0].([]models.UserAccess)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessByClientID indicates an expected call of GetAccessByClientID.
func (mr *MockUserAccessRepositoryMockRecorder) GetAccessByClientID(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessByClientID", reflect.TypeOf((*MockUserAccessRepository)(nil).GetAccessByClientID), ctx, clientID)
}

// GetAccessByUserID mocks base method.
func (m *MockUserAccessRepository) GetAccessByUserID(ctx context.Context, userID uuid.UUID) ([]models.UserAccess, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessByUserID", ctx, userID)
	ret0, _ := ret[0].([]models.UserAccess)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessByUserID indicates an expected call of GetAccessByUserID.
func (mr *MockUserAccessRepositoryMockRecorder) GetAccessByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessByUserID", reflect.TypeOf((*MockUserAccessRepository)(nil).GetAccessByUserID), ctx, userID)
}

// GrantAccess mocks base method.
func (m *MockUserAccessRepository) GrantAccess(ctx context.Context, access models.UserAccess) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrantAccess", ctx, access)
	ret0, _ := ret[0].(error)
	return ret0
}

// GrantAccess indicates an expected call of GrantAccess.
func (mr *MockUserAccessRepositoryMockRecorder) GrantAccess(ctx, access any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantAccess", reflect.TypeOf((*MockUserAccessRepository)(nil).GrantAccess), ctx, access)
}

// RevokeAccess mocks base method.
func (m *MockUserAccessRepository) RevokeAccess(ctx context.Context, userID, clientID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAccess", ctx, userID, clientID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAccess indicates an expected call of RevokeAccess.
func (mr *MockUserAccessRepositoryMockRecorder) RevokeAccess(ctx, userID, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAccess", reflect.TypeOf((*MockUserAccessRepository)(nil).RevokeAccess), ctx, userID, clientID)
}
