// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/user_access_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/user_access_service.go -destination=internal/tests/mocks/user_access_service_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	models "github.com/Iskolutions-Capstone-Dev-Team/One-Portal/internal/models"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserAccessService is a mock of UserAccessService interface.
type MockUserAccessService struct {
	ctrl     *gomock.Controller
	recorder *MockUserAccessServiceMockRecorder
	isgomock struct{}
}

// MockUserAccessServiceMockRecorder is the mock recorder for MockUserAccessService.
type MockUserAccessServiceMockRecorder struct {
	mock *MockUserAccessService
}

// NewMockUserAccessService creates a new mock instance.
func NewMockUserAccessService(ctrl *gomock.Controller) *MockUserAccessService {
	mock := &MockUserAccessService{ctrl: ctrl}
	mock.recorder = &MockUserAccessServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserAccessService) EXPECT() *MockUserAccessServiceMockRecorder {
	return m.recorder
}

// GetClientAccesses mocks base method.
func (m *MockUserAccessService) GetClientAccesses(ctx context.Context, clientID uuid.UUID) ([]models.UserAccess, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClientAccesses", ctx, clientID)
	ret0, _ := ret[0].([]models.UserAccess)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClientAccesses indicates an expected call of GetClientAccesses.
func (mr *MockUserAccessServiceMockRecorder) GetClientAccesses(ctx, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClientAccesses", reflect.TypeOf((*MockUserAccessService)(nil).GetClientAccesses), ctx, clientID)
}

// GetUserAccesses mocks base method.
func (m *MockUserAccessService) GetUserAccesses(ctx context.Context, userID uuid.UUID) ([]models.UserAccess, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAccesses", ctx, userID)
	ret0, _ := ret[0].([]models.UserAccess)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAccesses indicates an expected call of GetUserAccesses.
func (mr *MockUserAccessServiceMockRecorder) GetUserAccesses(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAccesses", reflect.TypeOf((*MockUserAccessService)(nil).GetUserAccesses), ctx, userID)
}

// GrantAccess mocks base method.
func (m *MockUserAccessService) GrantAccess(ctx context.Context, userID, clientID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GrantAccess", ctx, userID, clientID)
	ret0, _ := ret[0].(error)
	return ret0
}

// GrantAccess indicates an expected call of GrantAccess.
func (mr *MockUserAccessServiceMockRecorder) GrantAccess(ctx, userID, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantAccess", reflect.TypeOf((*MockUserAccessService)(nil).GrantAccess), ctx, userID, clientID)
}

// HasAccess mocks base method.
func (m *MockUserAccessService) HasAccess(ctx context.Context, userID, clientID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasAccess", ctx, userID, clientID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasAccess indicates an expected call of HasAccess.
func (mr *MockUserAccessServiceMockRecorder) HasAccess(ctx, userID, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasAccess", reflect.TypeOf((*MockUserAccessService)(nil).HasAccess), ctx, userID, clientID)
}

// RevokeAccess mocks base method.
func (m *MockUserAccessService) RevokeAccess(ctx context.Context, userID, clientID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeAccess", ctx, userID, clientID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeAccess indicates an expected call of RevokeAccess.
func (mr *MockUserAccessServiceMockRecorder) RevokeAccess(ctx, userID, clientID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeAccess", reflect.TypeOf((*MockUserAccessService)(nil).RevokeAccess), ctx, userID, clientID)
}
