services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: one_portal_frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    networks:
      - one_portal_network

# Backend Application
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: idp_backend
    restart: always
    env_file: ./.env
    environment:
      - GODEBUG=http2debug=0,asyncpreemptoff=1
    ports:
      - "8000:8080"
    volumes:
      - .env:/app/.env
    working_dir: /app
    networks:
      - one_portal_network
    depends_on:
      db:
        condition: service_healthy
    # Log rotation configuration
    logging:
      driver: "json-file"
      options:
        max-size: "30m"
        max-file: "3"

# Database Application
  oneportal_database:
    image: mysql:8.4
    container_name: unified_access_database
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      ADMIN_SQL_USER: ${ADMIN_SQL_USER}
      ADMIN_SQL_PASSWORD: ${ADMIN_SQL_PASSWORD}
      APP_USER: ${APP_USER}
      APP_PASSWORD: ${APP_PASSWORD}
    ports:
      - "3361:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    networks:
      - one_portal_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  one_portal_network:
    driver: bridge