services:
  # One Portal Backend (GHCR Image)
  backend:
    image: ghcr.io/iskolutions-capstone-dev-team/one-portal-backend:latest
    container_name: one_portal_backend
    restart: always
    env_file: ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "localhost:host-gateway"
    environment:
      - GODEBUG=http2debug=0,asyncpreemptoff=1
    ports:
      - "8080:8080"
    volumes:
      - .env:/app/.env
      - ./certs:/app/certs:ro
    working_dir: /app
    networks:
      - one_portal_network
    depends_on:
      oneportal_database:
        condition: service_healthy

  # One Portal Frontend (GHCR Image)
  frontend:
    image: ghcr.io/iskolutions-capstone-dev-team/one-portal-frontend:latest
    container_name: one_portal_frontend
    restart: always
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
      VITE_CLIENT_ID: ${VITE_CLIENT_ID}
      VITE_REDIRECT_URI: ${VITE_REDIRECT_URI}
      VITE_CLIENT_SECRET: ${VITE_CLIENT_SECRET}
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
      VITE_BACKEND_API_KEY: ${VITE_BACKEND_API_KEY}
      VITE_PROXY_TARGET_URL: ${VITE_PROXY_TARGET_URL}
    ports:
      - "5173:5173"
    networks:
      - one_portal_network
    depends_on:
      - backend

  # Database Service
  oneportal_database:
    image: mysql:8.4
    container_name: one_portal_database
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DB_NAME: ${MYSQL_DB_NAME}
      ADMIN_SQL_USER: ${ADMIN_SQL_USER}
      ADMIN_SQL_PASSWORD: ${ADMIN_SQL_PASSWORD}
      APP_USER: ${APP_USER}
      APP_PASSWORD: ${APP_PASSWORD}
    ports:
      - "3360:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    networks:
      - one_portal_network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:

networks:
  one_portal_network:
    driver: bridge
