export const SUFFIX_OPTIONS = [
  { label: "N/A", value: "N/A" },
  { label: "Jr.", value: "Jr." },
  { label: "Sr.", value: "Sr." },
  { label: "I", value: "I" },
  { label: "II", value: "II" },
  { label: "III", value: "III" },
  { label: "IV", value: "IV" },
  { label: "V", value: "V" },
  { label: "VI", value: "VI" },
  { label: "VII", value: "VII" },
  { label: "VIII", value: "VIII" },
  { label: "IX", value: "IX" },
  { label: "X", value: "X" },
  { label: "XI", value: "XI" },
  { label: "XII", value: "XII" },
  { label: "XIII", value: "XIII" },
  { label: "XIV", value: "XIV" },
  { label: "XV", value: "XV" },
  { label: "XVI", value: "XVI" },
  { label: "XVII", value: "XVII" },
  { label: "XVIII", value: "XVIII" },
  { label: "XIX", value: "XIX" },
  { label: "XX", value: "XX" },
];
